[project]
name = "runtime-config"
version = "0.1.0"
description = "Runtime config example for GLAIP SDK cookbook"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "glaip-sdk>=0.0.13",
]
