[project]
name = "core-observability"
version = "0.0.0"
description = "gllm_core.observability usage example"
requires-python = ">=3.11,<3.14"
readme = "README.md"
dependencies = [
    "gllm-core>=0.4.48.post1,<0.5.0",
    "opentelemetry-sdk",
]

[[tool.uv.index]]
name = "gen-ai-internal"
url = "https://glsdk.gdplabs.id/gen-ai-internal/simple/"

[tool.uv.sources]
gllm-core = { index = "gen-ai-internal" }
